// This file is auto-generated by Flutter's JSON serialization
// Generated by: flutter pub run build_runner build
//
// You do not need to manually edit this file.
// It is created based on the json_annotation decorators in gamification_models.dart

part of 'gamification_models.dart';

// ============================================================================
// JsonSerializableGenerator
// ============================================================================

UserProfile _$UserProfileFromJson(Map<String, dynamic> json) => UserProfile(
      id: json['id'] as String,
      name: json['name'] as String,
      email: json['email'] as String,
      joinedAt: DateTime.parse(json['joinedAt'] as String),
      dailyGoalMinutes: (json['dailyGoalMinutes'] as num?)?.toInt() ?? 10,
      dailyGoalAyahs: (json['dailyGoalAyahs'] as num?)?.toInt() ?? 0,
      level: (json['level'] as num?)?.toInt() ?? 1,
      xp: (json['xp'] as num?)?.toInt() ?? 0,
      longestStreak: (json['longestStreak'] as num?)?.toInt() ?? 0,
      avatarUrl: json['avatarUrl'] as String?,
      timezoneOffset: (json['timezoneOffset'] as num?)?.toInt() ?? 0,
    );

Map<String, dynamic> _$UserProfileToJson(UserProfile instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'email': instance.email,
      'joinedAt': instance.joinedAt.toIso8601String(),
      'dailyGoalMinutes': instance.dailyGoalMinutes,
      'dailyGoalAyahs': instance.dailyGoalAyahs,
      'level': instance.level,
      'xp': instance.xp,
      'longestStreak': instance.longestStreak,
      'avatarUrl': instance.avatarUrl,
      'timezoneOffset': instance.timezoneOffset,
    };

Session _$SessionFromJson(Map<String, dynamic> json) => Session(
      id: json['id'] as String,
      userId: json['userId'] as String,
      surah: (json['surah'] as num).toInt(),
      startAyah: (json['startAyah'] as num).toInt(),
      endAyah: (json['endAyah'] as num).toInt(),
      durationMinutes: (json['durationMinutes'] as num).toDouble(),
      date: json['date'] as String,
      accuracyScore: (json['accuracyScore'] as num).toDouble(),
      mode: json['mode'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      xpEarned: (json['xpEarned'] as num?)?.toInt() ?? 0,
    );

Map<String, dynamic> _$SessionToJson(Session instance) => <String, dynamic>{
      'id': instance.id,
      'userId': instance.userId,
      'surah': instance.surah,
      'startAyah': instance.startAyah,
      'endAyah': instance.endAyah,
      'durationMinutes': instance.durationMinutes,
      'date': instance.date,
      'accuracyScore': instance.accuracyScore,
      'mode': instance.mode,
      'createdAt': instance.createdAt.toIso8601String(),
      'xpEarned': instance.xpEarned,
    };

MemorizationProgress _$MemorizationProgressFromJson(
        Map<String, dynamic> json) =>
    MemorizationProgress(
      userId: json['userId'] as String,
      surah: (json['surah'] as num).toInt(),
      ayahCountMemorized:
          (json['ayahCountMemorized'] as num?)?.toInt() ?? 0,
      lastReviewedAt: json['lastReviewedAt'] == null
          ? null
          : DateTime.parse(json['lastReviewedAt'] as String),
      highAccuracySessions:
          Map<int, int>.from(json['highAccuracySessions'] as Map),
    );

Map<String, dynamic> _$MemorizationProgressToJson(
        MemorizationProgress instance) =>
    <String, dynamic>{
      'userId': instance.userId,
      'surah': instance.surah,
      'ayahCountMemorized': instance.ayahCountMemorized,
      'lastReviewedAt': instance.lastReviewedAt?.toIso8601String(),
      'highAccuracySessions': instance.highAccuracySessions,
    };

DailyProgress _$DailyProgressFromJson(Map<String, dynamic> json) =>
    DailyProgress(
      date: json['date'] as String,
      totalMinutes: (json['totalMinutes'] as num?)?.toInt() ?? 0,
      sessionsCount: (json['sessionsCount'] as num?)?.toInt() ?? 0,
      accuracyAverage:
          (json['accuracyAverage'] as num?)?.toDouble() ?? 0.0,
      status: json['status'] as String? ?? "not_started",
    );

Map<String, dynamic> _$DailyProgressToJson(DailyProgress instance) =>
    <String, dynamic>{
      'date': instance.date,
      'totalMinutes': instance.totalMinutes,
      'sessionsCount': instance.sessionsCount,
      'accuracyAverage': instance.accuracyAverage,
      'status': instance.status,
    };

StreakInfo _$StreakInfoFromJson(Map<String, dynamic> json) => StreakInfo(
      currentStreakDays:
          (json['currentStreakDays'] as num?)?.toInt() ?? 0,
      longestStreakDays:
          (json['longestStreakDays'] as num?)?.toInt() ?? 0,
      lastSessionDate: json['lastSessionDate'] as String?,
    );

Map<String, dynamic> _$StreakInfoToJson(StreakInfo instance) =>
    <String, dynamic>{
      'currentStreakDays': instance.currentStreakDays,
      'longestStreakDays': instance.longestStreakDays,
      'lastSessionDate': instance.lastSessionDate,
    };

LevelInfo _$LevelInfoFromJson(Map<String, dynamic> json) => LevelInfo(
      levelNumber: (json['levelNumber'] as num).toInt(),
      xpTotal: (json['xpTotal'] as num).toInt(),
      xpIntoLevel: (json['xpIntoLevel'] as num).toInt(),
      xpForNextLevel: (json['xpForNextLevel'] as num).toInt(),
      percentToNext: (json['percentToNext'] as num).toDouble(),
    );

Map<String, dynamic> _$LevelInfoToJson(LevelInfo instance) =>
    <String, dynamic>{
      'levelNumber': instance.levelNumber,
      'xpTotal': instance.xpTotal,
      'xpIntoLevel': instance.xpIntoLevel,
      'xpForNextLevel': instance.xpForNextLevel,
      'percentToNext': instance.percentToNext,
    };

TopSurah _$TopSurahFromJson(Map<String, dynamic> json) => TopSurah(
      surahNumber: (json['surahNumber'] as num).toInt(),
      surahName: json['surahName'] as String,
      memorizedPercent: (json['memorizedPercent'] as num).toDouble(),
      ayahCountMemorized: (json['ayahCountMemorized'] as num).toInt(),
      totalAyahs: (json['totalAyahs'] as num).toInt(),
    );

Map<String, dynamic> _$TopSurahToJson(TopSurah instance) => <String, dynamic>{
      'surahNumber': instance.surahNumber,
      'surahName': instance.surahName,
      'memorizedPercent': instance.memorizedPercent,
      'ayahCountMemorized': instance.ayahCountMemorized,
      'totalAyahs': instance.totalAyahs,
    };

HomeMetrics _$HomeMetricsFromJson(Map<String, dynamic> json) => HomeMetrics(
      isNewUser: json['isNewUser'] as bool,
      daily: json['daily'] as Map<String, dynamic>,
      streak: json['streak'] as Map<String, dynamic>,
      week: json['week'] as Map<String, dynamic>,
      level: json['level'] as Map<String, dynamic>,
      memorization: json['memorization'] as Map<String, dynamic>,
      lastSession: json['lastSession'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$HomeMetricsToJson(HomeMetrics instance) =>
    <String, dynamic>{
      'isNewUser': instance.isNewUser,
      'daily': instance.daily,
      'streak': instance.streak,
      'week': instance.week,
      'level': instance.level,
      'memorization': instance.memorization,
      'lastSession': instance.lastSession,
    };

